# Header
menu:
  Home: /
  Archives: /archives
  Résumé: /cv

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
# - tagcloud
# - archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
- category
- tagcloud
- archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics:
favicon: blog\themes\landscape\source\css\images\favicon.png
twitter: /Hex_iN_gaMe
google_plus:
fb_admins:
fb_app_id:

# SubNav
subnav:
rss: "/atom.xml"
